FEDERATION_SERVER="https://api.stellar.org/federation" 

ACCOUNTS=["", 
""
] 

[DOCUMENTATION] 
ORG_NAME="Cara Pembuatan Online" 
ORG_URL="https://cara.pembuatan.online" 
ORG_LOGO="https://cara.pembuatan.online/logo.png" 

[[CURRENCIES]] 
code="CARA" 
issuer="" 
status="live" 
name="CARA" 
desc="There will be only 1,000,000 CARA existed on SDEX for investors which will generate dividends as much as 2.5% per month for 10 years. The dividends send regularly to investor wallets every month." 
display_decimals=2 
image="https://cara.pembuatan.online/logo.png" 
